name: Continuous Integration
on: [push]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copiar ENV
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Ver si composer esta instalado
      run: which composer
    - name: Instalar dependencias (PHP Vendor)
      working-directory: ./Senasag/
      run: composer install
    - name: Generar llaves
      working-directory: ./Senasag/
      run: php artisan key:generate
    - name: Ejecutar test con PHPUnit
      working-directory: ./Senasag/
      run: vendor/bin/phpunit
